### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by luchoPenafiel** [petro232/meatpoint-maqueta#1]
https://github.com/petro232/meatpoint-maqueta/blob/main/css/styles.css#L1

```css
@font-face {
    font-family: 'brandon-light';
    src: url(../fonts/Brandon_light.otf);
}
@font-face {
.....
```

En lugar de llamar así a las fuentes, lo que podes hacer es lo siguiente:

```css
@font-face {
    font-family: 'brandon';
    src: url(../fonts/Brandon_light.otf);
    font-weight: 300;
}

@font-face {
    font-family: 'brandon';
    src: url(../fonts/Brandon_med.otf);
    font-weight: 500;
}
```
Fijate que lo que cambia es la url, obvio, y el font-wight. El `font-family` es el mismo para las dos (o todas las que quieras declarar. Eso te permite evitar definir el font-family cada vez que quieras cambiar de peso.
Podría hacer algo así:
```css
* {
   font-family: 'brandon';
}

#menu-nav li {
   ....
   font-weight: 500; /* medium */
   ....
}
```
